/* =====================================================================
   algorithm-c.js — Algorithm C: the min-factor exponent-spine generator
   Specification: algorithm.md §4C, full treatment in min_factor.md.

   Min-factor normal form (Theorem 2.10 / Claim M1).  Every n > 1 is
   uniquely n = p^e·r with p = spf(n), e = v_p(n) and r in the monoid
   B_p generated by the primes > p.  Summing over e re-assembles
   p·A_p = Θ_p, so this is a *refinement* of Algorithm B's index, not a
   different partition.

   Wheeled relaxation.  B_p is replaced by

       B̃_p = {1} ∪ { r ≥ p : gcd(r,W) = 1, p ∤ r } ⊇ B_p ,

   and **layer** (p,e) is the stream p^e·B̃_p minus the single
   non-composite element p (the case e = 1, r = 1).  Both retained
   constraints are load-bearing: r ≥ p stops a layer claiming numbers
   whose smallest factor is r, and p ∤ r keeps the layers of one prime
   disjoint (drop it and p^k is claimed k times).

   Records are (value, p, p^e, e, r, mp) with value = p^e·r; `mp` is the
   skip cursor, a multiple of p with mp ≥ r, which makes `next_adm`
   O(1) amortised (§4C.1: the ratio of skips to wheel steps is
   1/(κ_W·p) < 1 for every p > p_w ≥ 13).

   A layer is opened by the pop of its own spine element p^e, so no
   global N decides how many layers a prime gets, and the activation of
   p still fires exactly at n = p².

   What it buys (§4C.5 / min_factor.md §8): NOT touches — ops_C equals
   ops_B to within Θ(N^{2/3}/log N) — but output.  Every rejected
   candidate is reported as (spf, v_p, cofactor); the spine records are
   exactly the prime powers, in order.
   ===================================================================== */
import { MinHeap, buildWheel, assertExact, countLE, fmtInt as f } from './primegen-core.js';

export const meta = {
  id: 'C',
  title: 'Algorithm C — min-factor exponent-spine generator',
  ref: 'algorithm.md §4C · min_factor.md',
  usesWheel: true,
  blurb:
    'Algorithm B re-indexed by the min-factor normal form m = p^e·r: streams become layers (p,e). ' +
    'Same leading cost as B, strictly smaller claimant sets, and every rejected candidate is ' +
    'reported as (spf, v_p, cofactor) — a streaming min-factor oracle, not a faster prime generator.',
  streamNote:
    'A layer is created by the layer below it: popping the spine element p^e both extends the ' +
    'spine to p^{e+1} and opens the cloud of layer e, so no limit N is needed (§4C.2).',
};

/* ---------------------------------------------------------------------
   next_adm — least admissible multiplier > r: W-coprime and not a
   multiple of p.  `mp` is a multiple of p with mp ≥ r (skip cursor).
   ------------------------------------------------------------------ */
export function nextAdm(r, mp, p, W, step) {
  r += step[r % W];
  for (;;) {
    while (mp < r) mp += p;
    if (mp === r) r += step[r % W];
    else return [r, mp];
  }
}

const newStats = () => ({
  pops: 0,
  pushes: 0,
  candidates: 0,
  peakQueue: 0,
  reports: 0,
  ms: 0,
});

/* ---------------------------------------------------------------------
   §4C.2  C() — the unbounded generator.  `report(m, p, e, r)` receives
   the min-factor normal form of every W-coprime composite (Lemma 4C.4).
   ------------------------------------------------------------------ */
function* trace(limit, w, st, report) {
  const wh = buildWheel(w);
  const step = wh.step,
    W = wh.W;
  const Q = new MinHeap();
  const push = (v, p, pe, e, r, mp) => {
    if (v > limit) return; // bounded driver only
    assertExact(v, 'layer value p^e·r');
    Q.push([v, p, pe, e, r, mp]);
    st.pushes++;
    if (Q.size > st.peakQueue) st.peakQueue = Q.size;
  };

  for (const p of wh.primes) {
    if (p > limit) return;
    yield p; // p_1 … p_w
  }
  const primes = [];
  let act = 0,
    n = wh.first;

  while (n <= limit) {
    /* activation at n = p² exactly: all layers of p become reachable */
    while (act < primes.length && primes[act] * primes[act] <= n) {
      const p = primes[act++];
      const [r1, mp1] = nextAdm(p, p, p, W, step); // least admissible > p
      push(p * p, p, p * p, 2, 1, p); // spine head: the pure power p²
      push(p * r1, p, p, 1, r1, mp1); // layer-1 cloud head
    }
    st.candidates++;
    if (Q.size === 0 || Q.key() > n) {
      primes.push(n);
      yield n; // Thm 4C.3
    } else {
      let owner = null;
      while (Q.size && Q.key() === n) {
        /* drain all claimants — Claim M10: fewer than B's */
        const rec = Q.pop();
        st.pops++;
        const p = rec[1],
          pe = rec[2],
          e = rec[3],
          r = rec[4],
          mp = rec[5];
        if (owner === null || p < owner[0]) owner = [p, e, r]; // Lemma 4C.4
        if (r === 1) {
          /* n = p^e, a pure power: extend the spine, open layer e */
          push(pe * p, p, pe * p, e + 1, 1, p);
          const [r1, mp1] = nextAdm(p, p, p, W, step);
          push(pe * r1, p, pe, e, r1, mp1);
        } else {
          const [r2, mp2] = nextAdm(r, mp, p, W, step);
          push(pe * r2, p, pe, e, r2, mp2);
        }
      }
      st.reports++;
      if (report) report(n, owner[0], owner[1], owner[2]);
    }
    n += step[n % W];
  }
}

export function* stream({ w = 6, limit = Infinity, report = null } = {}) {
  yield* trace(limit, w, newStats(), report);
}

/* ---- oracle validation (small m only; trial division) -------------- */
function smallestFactor(m) {
  if (m % 2 === 0) return 2;
  for (let d = 3; d * d <= m; d += 2) if (m % d === 0) return d;
  return m;
}
function checkForm(m, p, e, r) {
  if (r % p === 0) return false; // p ∤ r forces e = v_p(m)
  let pe = 1;
  for (let i = 0; i < e; i++) pe *= p;
  if (pe * r !== m) return false;
  return smallestFactor(m) === p; // p = spf(m)
}

export function run(limit, { w = 6, report = null, oracleMax = 20000 } = {}) {
  assertExact(limit, 'N');
  const st = newStats();
  st.sample = [];
  st.sample847 = null;
  st.oracle = { limit: Math.min(limit, oracleMax), tested: 0, bad: 0 };
  const primes = [];
  const hook = (m, p, e, r) => {
    if (st.sample.length < 12) st.sample.push([m, p, e, r]);
    if (m === 847) st.sample847 = [p, e, r]; // 7·11², the M10 witness
    if (m <= st.oracle.limit) {
      st.oracle.tested++;
      if (!checkForm(m, p, e, r)) st.oracle.bad++;
    }
    if (report) report(m, p, e, r);
  };
  const t0 = performance.now();
  for (const p of trace(limit, w, st, hook)) primes.push(p);
  st.ms = performance.now() - t0;
  return { primes, stats: st, wheel: buildWheel(w) };
}

/* §7.4  restart, layer by layer: state of layer (p,e) at segment start X */
function admGE(p, y, wh) {
  let r = wh.nextGE(Math.max(1, y));
  while (r % p === 0) r = wh.next(r); // ≤ ⌈g_W/p⌉+1 wheel steps
  return r;
}
export function layerStateAt(p, e, X, wh) {
  let pe = 1;
  for (let i = 0; i < e; i++) pe *= p;
  const r1 = nextAdm(p, p, p, wh.W, wh.step)[0];
  const r0 = pe >= X && e >= 2 ? 1 : Math.max(r1, admGE(p, Math.ceil(X / pe), wh));
  return { pe, e, r: r0, mp: p * Math.ceil(r0 / p), v: pe * r0 };
}

export function summary({ primes, stats: st, wheel: wh }, N) {
  const pw = wh.primes[wh.primes.length - 1];
  const opsB = wh.kappa * N * (Math.log(Math.log(Math.sqrt(N))) - Math.log(Math.log(pw)));
  const piRoot = countLE(primes, Math.floor(Math.sqrt(N)));
  const lines = [
    [
      `wheel             : W = ${f(wh.W)}   κ_W = ${wh.kappa.toFixed(4)}   ` +
        `p_w = ${pw}   p_{w+1} = ${wh.first}`,
    ],
    [`candidates seen   : ${f(st.candidates)}   (κ_W·N ≈ ${f(wh.kappa * N)})`],
    [
      `queue pops        : ${f(st.pops)}   = ${(st.pops / N).toFixed(3)}·N   ` +
        `(ops_B model ≈ ${f(opsB)}; §4C.4 gap ≈ 10⁻⁴·N)`,
    ],
    [
      `records (peak)    : ${f(st.peakQueue)}   vs 2·π(√N) = ${f(2 * piRoot)} ` +
        `— uniform form; the thinned spine (§7.3) reaches (1+o(1))·π(√N) = ${f(piRoot)}`,
    ],
    [`normal forms      : ${f(st.reports)} composites reported as (spf, v_p, cofactor)`],
  ];
  const ok = st.oracle.bad === 0 && st.oracle.tested > 0;
  lines.push([
    `min-factor oracle : ${f(st.oracle.tested)} forms checked for m ≤ ${f(st.oracle.limit)}   ` +
      (ok ? '✓ all exact (Lemma 4C.4)' : `✗ ${st.oracle.bad} wrong`),
    ok ? 'pass' : 'fail',
  ]);
  lines.push(['']);
  lines.push(['sample of the emitted stream   n ↦ ( spf, v_spf, cofactor ):']);
  for (const [m, p, e, r] of st.sample) lines.push([`   ${f(m).padStart(11)} = ${p}^${e} · ${r}`]);
  if (st.sample847)
    lines.push([
      `   847 = 7·11² → (${st.sample847.join(', ')})   ` +
        `— B claims it twice, C once (Lemma 4C.5)`,
      'acc',
    ]);
  else lines.push([`   (847 = 7·11² needs w ≤ 3 to be a candidate — set w = 3 to see it)`, 'dim']);
  lines.push(['']);
  lines.push(['§7.4 restart is still O(1), now layer by layer:']);
  for (const [p, e, X] of [
    [17, 1, 1000000],
    [17, 2, 1000000],
    [101, 1, 50000],
    [1009, 2, 4000000],
  ]) {
    const s = layerStateAt(p, e, X, wh);
    lines.push([
      `   (p,e)=(${String(p).padStart(5)},${e})  X=${f(X).padStart(11)}  →  ` +
        `p^e=${f(s.pe).padStart(9)}  r₀=${f(s.r).padStart(9)}  v=${f(s.v)}`,
    ]);
  }
  lines.push(['']);
  lines.push(['Same leading cost as B — the layers only partition the multiples of p that', 'dim']);
  lines.push(['B handles in one stream. Choose C for what it emits: ω, Ω, μ, radical,', 'dim']);
  lines.push(['squarefree tests, smooth/rough enumeration by layer index, and the prime', 'dim']);
  lines.push(['powers for free (the spine records are exactly p^e, e ≥ 2, in order).', 'dim']);
  return lines;
}
