/-
§2–§8 of `experiments/primegen/min_factor.md`: Algorithm C, the min-factor exponent spine.

* `Bmono p r`                   — §1  : `B_p`, the multiplicative monoid generated by the
                                        primes `> p`  (`B_p = {1} ⊎ R_{>p}`)
* `exists_valuation_split`,
  `valuation_eq`                — the run-length split at the head, existence + uniqueness
* `exists_unique_normal_form`   — **Claim M1**: `n = p^e·r`, `p = spf n`, `e = v_p n`, `r ∈ B_p`,
                                  uniquely
* `exists_unique_cone_split`,
  `cone_recursion`,
  `not_one_step_cone`           — **Claim M2**, in the two forms that are true, plus the
                                  counterexample `9 ∈ B_2`, `9 = 3·3`, `3 ∉ B_3` refuting the
                                  one-step form printed in §2.2 (see Correction M2′ there)
* `prime_of_bmono_of_lt_sq`     — **Claim M3** (strict phase separation, `(p+1)²`)
* `causality`                   — **Claim M4** (the wider margin `2m/p`)
* `Adm`, `ClaimsC`              — §4/§5: the wheeled relaxation `B̃_p` and the layer streams
* `coverage`, `not_prime_of_claims`, `sq_le_of_claims`,
  `prime_iff_forall_not_claims` — **Claims M6–M9** (set form; the loop induction is open, as
                                  it is for Algorithm B)
* `claimsB_of_claimsC`,
  `claimants_subset`,
  `not_claims_847_eleven`       — **Claim M10**: `claimants_C ⊆ claimants_B`, and the smallest
                                  strictness witness `847 = 7·11²`
* `oracle`                      — **Claim M11**: the minimum claimant carries the full normal
                                  form `(spf, v_p, cofactor)`
* `normalForm`, `dupStatsC`     — executable model, and the §7.1 measurement
-/
import Mathlib
import Primegen.Ownership
import Primegen.Wheel
import Primegen.AlgorithmB

namespace Primegen
namespace MinFac

/-! ### `B_p` — the multiplier cloud is a monoid, not an interval (§0, §1) -/

/-- `B_p = { r ≥ 1 : q prime, q ∣ r ⟹ q > p }`, the monoid generated by the primes `> p`. -/
def Bmono (p r : ℕ) : Prop := 1 ≤ r ∧ ∀ q, Nat.Prime q → q ∣ r → p < q

instance (p r : ℕ) : Decidable (Bmono p r) :=
  decidable_of_iff (1 ≤ r ∧ ∀ q ∈ Finset.range (r + 1), Nat.Prime q → q ∣ r → p < q) <| by
    constructor
    · rintro ⟨h1, h⟩
      refine ⟨h1, fun q hq hqr => h q ?_ hq hqr⟩
      have := Nat.le_of_dvd (by omega) hqr
      exact Finset.mem_range.mpr (by omega)
    · rintro ⟨h1, h⟩
      exact ⟨h1, fun q _ hq hqr => h q hq hqr⟩

theorem Bmono.one_le {p r : ℕ} (h : Bmono p r) : 1 ≤ r := by
  obtain ⟨h1, -⟩ := h
  exact h1

theorem Bmono.factors {p r : ℕ} (h : Bmono p r) : ∀ q, Nat.Prime q → q ∣ r → p < q := by
  obtain ⟨-, h2⟩ := h
  exact h2

/-- **Remark M-X, one half.**  `r ∈ B_p` is a coprimality statement: `p ∤ r` for free. -/
theorem Bmono.not_dvd {p r : ℕ} (hp : Nat.Prime p) (h : Bmono p r) : ¬ p ∣ r := fun hd =>
  absurd (h.factors p hp hd) (lt_irrefl p)

/-- Every element of `B_p` other than `1` exceeds `p` — the constraint `r ≥ p` of §4.2. -/
theorem Bmono.lt {p r : ℕ} (h : Bmono p r) (hr : 1 < r) : p < r := by
  have hq : Nat.Prime r.minFac := Nat.minFac_prime (by omega)
  exact lt_of_lt_of_le (h.factors _ hq (Nat.minFac_dvd r)) (Nat.minFac_le (by omega))

theorem bmono_one (p : ℕ) : Bmono p 1 :=
  ⟨le_rfl, fun q hq hqr => absurd (Nat.dvd_one.mp hqr) hq.ne_one⟩

theorem bmono_of_prime_lt {p q : ℕ} (hq : Nat.Prime q) (hpq : p < q) : Bmono p q :=
  ⟨hq.one_lt.le, fun s hs hsq => by
    rw [(Nat.prime_dvd_prime_iff_eq hs hq).mp hsq]; exact hpq⟩

theorem Bmono.of_dvd {p r s : ℕ} (h : Bmono p r) (hs : 1 ≤ s) (hsr : s ∣ r) : Bmono p s :=
  ⟨hs, fun q hq hqs => h.factors q hq (hqs.trans hsr)⟩

/-- `B_p` is the roughness predicate of §2 shifted by one: `B_p = {r ≥ 1 : Rough (p+1) r}`.
This is Remark M-X in the form the development can use: nothing new is proved about
coprimality, the index is merely re-based. -/
theorem bmono_iff_rough {p r : ℕ} : Bmono p r ↔ 1 ≤ r ∧ Rough (p + 1) r := by
  constructor
  · rintro ⟨h1, h⟩
    refine ⟨h1, rough_iff.mpr fun q hq hqr => ?_⟩
    have := h q hq hqr
    omega
  · rintro ⟨h1, h⟩
    refine ⟨h1, fun q hq hqr => ?_⟩
    have := rough_iff.mp h q hq hqr
    omega

/-- **Claim M3 (phase separation, strict form).**  `1 < r < (p+1)²` and `r ∈ B_p` force `r`
prime.  One step stricter than `Primegen.prime_of_rough_of_lt_sq`, and derived from it. -/
theorem prime_of_bmono_of_lt_sq {p r : ℕ} (h1 : 1 < r) (hB : Bmono p r)
    (hlt : r < (p + 1) * (p + 1)) : Nat.Prime r :=
  prime_of_rough_of_lt_sq h1 (bmono_iff_rough.mp hB).2 hlt

/-! ### Small power facts (used throughout; stated once) -/

theorem self_le_pow {p e : ℕ} (hp : 0 < p) (he : 1 ≤ e) : p ≤ p ^ e := by
  calc p = p ^ 1 := (pow_one p).symm
    _ ≤ p ^ e := Nat.pow_le_pow_right hp he

theorem one_lt_pow' {p e : ℕ} (hp : 1 < p) (he : 1 ≤ e) : 1 < p ^ e :=
  lt_of_lt_of_le hp (self_le_pow (by omega) he)

theorem not_prime_mul' {a b : ℕ} (ha : 1 < a) (hb : 1 < b) : ¬ Nat.Prime (a * b) := by
  intro h
  rcases h.eq_one_or_self_of_dvd a ⟨b, rfl⟩ with h1 | h2
  · omega
  · have hab : a * 1 = a * b := by rw [mul_one]; exact h2
    have := Nat.eq_of_mul_eq_mul_left (by omega : 0 < a) hab
    omega

/-! ### The run-length split at the head (Claim M1, mechanics) -/

private theorem exists_split_aux {p : ℕ} (hp : 2 ≤ p) :
    ∀ fuel n, 0 < n → n ≤ fuel → ∃ e r, 0 < r ∧ n = p ^ e * r ∧ ¬ p ∣ r := by
  intro fuel
  induction fuel with
  | zero => intro n hn hle; omega
  | succ fuel ih =>
    intro n hn hle
    by_cases h : p ∣ n
    · obtain ⟨m, rfl⟩ := h
      have hm : 0 < m := Nat.pos_of_ne_zero (by intro h0; simp [h0] at hn)
      have h2 : 2 * m ≤ p * m := Nat.mul_le_mul hp le_rfl
      obtain ⟨e, r, hr0, hmr, hnd⟩ := ih m hm (by omega)
      exact ⟨e + 1, r, hr0, by rw [hmr, pow_succ]; ring, hnd⟩
    · exact ⟨0, n, hn, by rw [pow_zero, one_mul], h⟩

/-- Existence of the head split `n = p^e·r` with `p ∤ r`. -/
theorem exists_valuation_split {p : ℕ} (hp : 2 ≤ p) {n : ℕ} (hn : 0 < n) :
    ∃ e r, 0 < r ∧ n = p ^ e * r ∧ ¬ p ∣ r :=
  exists_split_aux hp n n hn le_rfl

/-- Uniqueness of the head split: `p ∤ r` pins the exponent to `v_p(n)`. -/
theorem valuation_eq {p e e' r r' : ℕ} (hp : Nat.Prime p)
    (hr : ¬ p ∣ r) (hr' : ¬ p ∣ r') (h : p ^ e * r = p ^ e' * r') : e = e' ∧ r = r' := by
  have key : ∀ a b x y : ℕ, a ≤ b → ¬ p ∣ x → p ^ a * x = p ^ b * y → a = b := by
    intro a b x y hab hx heq
    by_contra hne
    have hlt : a < b := lt_of_le_of_ne hab hne
    have hsplit : p ^ a * (p ^ (b - a) * y) = p ^ b * y := by
      rw [← mul_assoc, ← pow_add, Nat.add_sub_cancel' hab]
    have hx' : x = p ^ (b - a) * y :=
      Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos a) (by rw [heq, hsplit])
    exact hx (by rw [hx']; exact (dvd_pow_self p (by omega : b - a ≠ 0)).mul_right y)
  rcases le_total e e' with hle | hle
  · have he := key e e' r r' hle hr h
    subst he
    exact ⟨rfl, Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos _) h⟩
  · have he := key e' e r' r hle hr' h.symm
    subst he
    exact ⟨rfl, Nat.eq_of_mul_eq_mul_left (pow_pos hp.pos _) h⟩

/-! ### Claim M1 — the min-factor normal form -/

/-- Existence half of Claim M1, with the owner exhibited as `spf n`. -/
theorem exists_normal_form {n : ℕ} (h1 : 1 < n) :
    ∃ e r, 1 ≤ e ∧ Bmono n.minFac r ∧ n = n.minFac ^ e * r := by
  have hp : Nat.Prime n.minFac := Nat.minFac_prime (by omega)
  obtain ⟨e, r, hr0, hn, hnd⟩ := exists_valuation_split hp.two_le (n := n) (by omega)
  have hrn : r ∣ n := ⟨n.minFac ^ e, by rw [hn]; ring⟩
  refine ⟨e, r, ?_, ⟨by omega, ?_⟩, hn⟩
  · rcases Nat.eq_zero_or_pos e with rfl | he
    · rw [pow_zero, one_mul] at hn
      have hd : n.minFac ∣ r := by rw [← hn]; exact Nat.minFac_dvd n
      exact absurd hd hnd
    · exact he
  · intro q hq hqr
    have hle : n.minFac ≤ q := Nat.minFac_le_of_dvd hq.two_le (hqr.trans hrn)
    rcases eq_or_lt_of_le hle with heq | hlt
    · exact absurd (by rw [heq]; exact hqr) hnd
    · exact hlt

/-- In any factorisation `n = p^e·r` with `e ≥ 1` and `r ∈ B_p`, the prime is forced:
`p = spf n`.  (The `p = spf(n)` clause of Claim M1.) -/
theorem minFac_eq_of_normal_form {n p e r : ℕ} (hp : Nat.Prime p) (he : 1 ≤ e)
    (hB : Bmono p r) (hn : n = p ^ e * r) : p = n.minFac := by
  have hr1 : 1 ≤ r := hB.one_le
  have hple : p ≤ n := by
    rw [hn]
    calc p ≤ p ^ e := self_le_pow hp.pos he
      _ = p ^ e * 1 := by rw [mul_one]
      _ ≤ p ^ e * r := Nat.mul_le_mul le_rfl hr1
  have h1n : 1 < n := lt_of_lt_of_le hp.one_lt hple
  have hpn : p ∣ n := by
    rw [hn]
    exact (dvd_pow_self p (by omega : e ≠ 0)).mul_right r
  have hqle : n.minFac ≤ p := Nat.minFac_le_of_dvd hp.two_le hpn
  have hq : Nat.Prime n.minFac := Nat.minFac_prime (by omega)
  have hqd : n.minFac ∣ p ^ e * r := by rw [← hn]; exact Nat.minFac_dvd n
  rcases (Nat.Prime.dvd_mul hq).mp hqd with h | h
  · have := (Nat.prime_dvd_prime_iff_eq hq hp).mp (hq.dvd_of_dvd_pow h)
    omega
  · have := hB.factors _ hq h
    omega

/-- **Claim M1 (min-factor normal form).**  Every `n > 1` factors *uniquely* as `p^e·r` with
`p` prime, `e ≥ 1`, `r ∈ B_p`; and then `p = spf n`, `e = v_p n`, `r = n/p^e`.  This is the
refinement of the ownership partition that Algorithm C indexes by. -/
theorem exists_unique_normal_form {n : ℕ} (h1 : 1 < n) :
    ∃! t : ℕ × ℕ × ℕ,
      Nat.Prime t.1 ∧ 1 ≤ t.2.1 ∧ Bmono t.1 t.2.2 ∧ n = t.1 ^ t.2.1 * t.2.2 := by
  obtain ⟨e, r, he, hB, hn⟩ := exists_normal_form h1
  refine ⟨(n.minFac, e, r), ⟨Nat.minFac_prime (by omega), he, hB, hn⟩, ?_⟩
  rintro ⟨p', e', r'⟩ ⟨hp', he', hB', hn'⟩
  have hpp : p' = n.minFac := minFac_eq_of_normal_form hp' he' hB' hn'
  have hB'' : Bmono n.minFac r' := by rw [← hpp]; exact hB'
  have hval : n.minFac ^ e' * r' = n.minFac ^ e * r := by
    rw [← hn, ← hpp]; exact hn'.symm
  obtain ⟨hee, hrr⟩ :=
    valuation_eq (Nat.minFac_prime (by omega : n ≠ 1))
      (hB''.not_dvd (Nat.minFac_prime (by omega))) (hB.not_dvd (Nat.minFac_prime (by omega)))
      hval
  simp [Prod.ext_iff, hpp, hee, hrr]

/-! ### Claim M2 — delegation, and the correction the formalisation forces

The one-step form printed in `min_factor.md` §2.2, `B_p = {1} ⊎ ⨄_{q>p} q·B_q`, is **false**:
`9 ∈ B_2`, but `9 = 3·3` and `3 ∉ B_3`, and `3` is `9`'s only prime factor.  The gap is in the
quoted proof, which produces `r ∈ q^{v_q(r)}·B_q` and then reads it as `r ∈ q·B_q`.  Two
repairs, both proved here: run-length encode the head (`cone_recursion`, which is just M1
applied to `r`), or relax the cone from `B_q` to `{s : spf s ≥ q}` (`exists_unique_cone_split`,
which keeps the *disjointness* that makes it a partition). -/

/-- **Claim M2, one-step form, repaired.**  `B_p \ {1} = ⨄_{q>p} q·{s : spf s ≥ q}`, with
`q = spf r` the unique choice.  `Rough q s` is exactly "every prime factor of `s` is `≥ q`". -/
theorem exists_unique_cone_split {p r : ℕ} (hB : Bmono p r) (hr : 1 < r) :
    ∃! qs : ℕ × ℕ,
      Nat.Prime qs.1 ∧ p < qs.1 ∧ 0 < qs.2 ∧ Rough qs.1 qs.2 ∧ r = qs.1 * qs.2 := by
  have hq : Nat.Prime r.minFac := Nat.minFac_prime (by omega)
  have hqd : r.minFac ∣ r := Nat.minFac_dvd r
  have hmul : r.minFac * (r / r.minFac) = r := Nat.mul_div_cancel' hqd
  have hsdvd : (r / r.minFac) ∣ r := ⟨r.minFac, by rw [Nat.mul_comm]; exact hmul.symm⟩
  have hspos : 0 < r / r.minFac := by
    rcases Nat.eq_zero_or_pos (r / r.minFac) with h | h
    · rw [h, Nat.mul_zero] at hmul; omega
    · exact h
  refine ⟨(r.minFac, r / r.minFac),
    ⟨hq, hB.factors _ hq hqd, hspos, rough_iff.mpr fun t ht htd =>
      Nat.minFac_le_of_dvd ht.two_le (htd.trans hsdvd), hmul.symm⟩, ?_⟩
  rintro ⟨q, s⟩ ⟨hqp, hpq, hspos', hrough, hrs⟩
  have hqdvd : q ∣ r := ⟨s, hrs⟩
  have hle : r.minFac ≤ q := Nat.minFac_le_of_dvd hqp.two_le hqdvd
  have hqeq : q = r.minFac := by
    have hd : r.minFac ∣ q * s := by rw [← hrs]; exact hqd
    rcases (Nat.Prime.dvd_mul hq).mp hd with h | h
    · exact ((Nat.prime_dvd_prime_iff_eq hq hqp).mp h).symm
    · have := rough_iff.mp hrough _ hq h
      omega
  have hseq : s = r / r.minFac := by
    refine Nat.eq_of_mul_eq_mul_left hq.pos ?_
    rw [hmul, ← hqeq, ← hrs]
  simp [Prod.ext_iff, hqeq, hseq]

/-- **Claim M2, run-length form.**  `B_p \ {1} = ⨄_{q>p} ⨄_{e≥1} q^e·B_q`: the cone of `p` is
generated by the cones of the larger primes, with the loop `q → q` run-length encoded.  This is
Claim M1 applied to `r`, which is exactly the "one-step unfolding" §2.2 was after. -/
theorem cone_recursion {p r : ℕ} (hB : Bmono p r) (hr : 1 < r) :
    ∃ q e s, Nat.Prime q ∧ p < q ∧ 1 ≤ e ∧ Bmono q s ∧ r = q ^ e * s := by
  obtain ⟨e, s, he, hBs, hrs⟩ := exists_normal_form hr
  have hq : Nat.Prime r.minFac := Nat.minFac_prime (by omega)
  exact ⟨r.minFac, e, s, hq, hB.factors _ hq (Nat.minFac_dvd r), he, hBs, hrs⟩

/-- **Correction M2′.**  The form displayed in §2.2 is false, and `9` is the least witness:
`9 ∈ B_2`, yet `9 ∉ ⨄_{q>2} q·B_q`. -/
theorem not_one_step_cone :
    Bmono 2 9 ∧ ¬ ∃ q s, Nat.Prime q ∧ 2 < q ∧ Bmono q s ∧ 9 = q * s := by
  constructor
  · refine ⟨by norm_num, fun q hq hq9 => ?_⟩
    have h9 : q ∣ 3 ^ 2 := by
      have h : (3 : ℕ) ^ 2 = 9 := by norm_num
      rw [h]; exact hq9
    have h3 : q = 3 :=
      (Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow h9)
    omega
  · rintro ⟨q, s, hq, hq2, hBs, h9⟩
    have hqd : q ∣ 3 ^ 2 := ⟨s, by rw [← h9]; norm_num⟩
    have hq3 : q = 3 :=
      (Nat.prime_dvd_prime_iff_eq hq (by norm_num)).mp (hq.dvd_of_dvd_pow hqd)
    subst hq3
    have hs : s = 3 := by omega
    subst hs
    exact absurd (hBs.factors 3 (by norm_num) dvd_rfl) (by norm_num)

/-! ### Claim M4 — causality, with the wider margin -/

/-- **Claim M4 (causality).**  The next admissible multiplier of layer `(p,e)` after `r` lies
strictly below the current value `m = p^e·r`: Algorithm C never needs to know anything about an
integer it has not already scanned.  The margin is `2m/p`, wider than Algorithm B's `m/2`. -/
theorem causality {p e r : ℕ} (hp : Nat.Prime p) (hp2 : 2 < p) (he : 1 ≤ e)
    (hB : Bmono p r) (hr : 1 < r) :
    ∃ r', r < r' ∧ Bmono p r' ∧ r' < p ^ e * r := by
  obtain ⟨q, hq, hrq, hq2⟩ := Nat.exists_prime_lt_and_le_two_mul r (by omega)
  refine ⟨q, hrq, bmono_of_prime_lt hq (lt_trans (hB.lt hr) hrq), ?_⟩
  have h3 : 3 * r ≤ p * r := Nat.mul_le_mul (by omega) le_rfl
  have h4 : p * r ≤ p ^ e * r := Nat.mul_le_mul (self_le_pow hp.pos he) le_rfl
  omega

/-! ### §4/§5 — the wheeled relaxation `B̃_p` and the layer streams -/

/-- `B̃_p = {1} ∪ { r ≥ p : gcd(r,W) = 1, p ∤ r }` of §1/§4.2: the two constraints kept exactly
are `r ≥ p` (or `r = 1`) and `p ∤ r`. -/
def Adm (W p r : ℕ) : Prop := r = 1 ∨ (p ≤ r ∧ Nat.Coprime r W ∧ ¬ p ∣ r)

theorem adm_iff {W p r : ℕ} :
    Adm W p r ↔ r = 1 ∨ (p ≤ r ∧ Nat.Coprime r W ∧ ¬ p ∣ r) := Iff.rfl

/-- `p ∤ r` holds on all of `B̃_p`, including its unit — this is what makes the layers of one
prime disjoint (§4.2, point 2). -/
theorem Adm.not_dvd {W p r : ℕ} (hp : Nat.Prime p) (h : Adm W p r) : ¬ p ∣ r := by
  rcases h with rfl | ⟨-, -, h⟩
  · exact fun hd => hp.ne_one (Nat.dvd_one.mp hd)
  · exact h

theorem Adm.le_of_ne_one {W p r : ℕ} (h : Adm W p r) (hr : r ≠ 1) : p ≤ r := by
  rcases h with h | ⟨h, -, -⟩
  · exact absurd h hr
  · exact h

/-- `B_p ⊆ B̃_p` for the multipliers that actually occur: a cofactor of a `W`-coprime number. -/
theorem adm_of_bmono {W p r m : ℕ} (hp : Nat.Prime p) (hB : Bmono p r) (hrm : r ∣ m)
    (hcop : Nat.Coprime m W) : Adm W p r := by
  rcases eq_or_lt_of_le hB.one_le with h | h
  · exact Or.inl h.symm
  · exact Or.inr ⟨le_of_lt (hB.lt h), Nat.Coprime.coprime_dvd_left hrm hcop, hB.not_dvd hp⟩

/-- "Layer `(p,e)` claims `m`": `m ∈ p^e·B̃_p`, minus the single non-composite element
`p = p^1·1` (§4.2, point 3). -/
def ClaimsC (W p e m : ℕ) : Prop :=
  Nat.Prime p ∧ ¬ p ∣ W ∧ 1 ≤ e ∧ ∃ r, Adm W p r ∧ (e ≠ 1 ∨ r ≠ 1) ∧ m = p ^ e * r

/-- The spine records (`r = 1`) are exactly the prime powers `p^e`, `e ≥ 2` (§8). -/
theorem spine_claims {W p e : ℕ} (hp : Nat.Prime p) (hnd : ¬ p ∣ W) (he : 2 ≤ e) :
    ClaimsC W p e (p ^ e) :=
  ⟨hp, hnd, by omega, 1, Or.inl rfl, Or.inl (by omega), by rw [mul_one]⟩

/-- **Claim M6 (coverage).**  Every `W`-coprime composite `m` is a value of layer
`(spf m, v_{spf m} m)`. -/
theorem coverage {W m : ℕ} (h1 : 1 < m) (hc : ¬ Nat.Prime m) (hcop : Nat.Coprime m W) :
    ∃ e, ClaimsC W m.minFac e m := by
  have hp : Nat.Prime m.minFac := Nat.minFac_prime (by omega)
  obtain ⟨e, r, he, hB, hm⟩ := exists_normal_form h1
  have hrm : r ∣ m := ⟨m.minFac ^ e, by rw [hm]; ring⟩
  refine ⟨e, hp, AlgB.not_dvd_of_coprime hp (Nat.minFac_dvd m) hcop, he, r,
    adm_of_bmono hp hB hrm hcop, ?_, hm⟩
  by_contra hcon
  push_neg at hcon
  obtain ⟨he1, hr1⟩ := hcon
  rw [he1, hr1, pow_one, mul_one] at hm
  exact hc (by rw [hm]; exact hp)

/-- **Claim M7 (soundness).**  Every key of every layer is composite; a prime candidate is
never claimed. -/
theorem not_prime_of_claims {W p e m : ℕ} (h : ClaimsC W p e m) : ¬ Nat.Prime m := by
  obtain ⟨hp, -, he, r, hadm, hne, rfl⟩ := h
  rcases hadm with rfl | ⟨hpr, -, -⟩
  · have he2 : 2 ≤ e := by
      rcases hne with h | h
      · omega
      · exact absurd rfl h
    have he1 : e - 1 + 1 = e := by omega
    have hsplit : p ^ e * 1 = p ^ (e - 1) * p := by rw [mul_one, ← pow_succ, he1]
    rw [hsplit]
    exact not_prime_mul' (one_lt_pow' hp.one_lt (by omega)) hp.one_lt
  · exact not_prime_mul' (one_lt_pow' hp.one_lt he) (by have := hp.two_le; omega)

/-- **Claim M8 (no early claims), head half.**  Every key of a layer of `p` is `≥ p²`, so
deferred activation at `n = p²` loses nothing. -/
theorem sq_le_of_claims {W p e m : ℕ} (h : ClaimsC W p e m) : p * p ≤ m := by
  obtain ⟨hp, -, he, r, hadm, hne, rfl⟩ := h
  rcases hadm with rfl | ⟨hpr, -, -⟩
  · have he2 : 2 ≤ e := by
      rcases hne with h | h
      · omega
      · exact absurd rfl h
    rw [mul_one]
    calc p * p = p ^ 2 := by ring
      _ ≤ p ^ e := Nat.pow_le_pow_right hp.pos he2
  · exact Nat.mul_le_mul (self_le_pow hp.pos he) hpr

/-- **Claim M9 (decision rule), set form.**  A `W`-coprime candidate is prime iff no layer
claims it.  (The queue/loop induction is still open, exactly as for Algorithm B.) -/
theorem prime_iff_forall_not_claims {W n : ℕ} (h1 : 1 < n) (hcop : Nat.Coprime n W) :
    Nat.Prime n ↔ ∀ p e, ¬ ClaimsC W p e n := by
  refine ⟨fun hn p e hcl => not_prime_of_claims hcl hn, fun h => ?_⟩
  by_contra hc
  obtain ⟨e, hcl⟩ := coverage h1 hc hcop
  exact h _ e hcl

/-! ### Claim M10 — `claimants_C ⊆ claimants_B`, strictly -/

/-- **Claim M10, inclusion.**  If layer `(p,e)` of Algorithm C claims `m`, then the single
stream of `p` in Algorithm B claims it too: the multiplier is `a = p^{e-1}·r`.  This is the
statement that makes "C is B with a finer index" precise (§11, item 1). -/
theorem claimsB_of_claimsC {W p e m : ℕ} (h : ClaimsC W p e m) : AlgB.Claims W p m := by
  obtain ⟨hp, hnd, he, r, hadm, hne, rfl⟩ := h
  have he1 : e - 1 + 1 = e := by omega
  have hpe : p ^ (e - 1) * p = p ^ e := by rw [← pow_succ, he1]
  refine ⟨hp, hnd, p ^ (e - 1) * r, ?_, ?_, ?_⟩
  · refine Nat.Coprime.mul ?_ ?_
    · exact Nat.Coprime.pow_left _ ((Nat.Prime.coprime_iff_not_dvd hp).mpr hnd)
    · rcases hadm with rfl | ⟨-, hc, -⟩
      · exact Nat.coprime_one_left W
      · exact hc
  · rcases hadm with rfl | ⟨hpr, -, -⟩
    · have he2 : 2 ≤ e := by
        rcases hne with h | h
        · omega
        · exact absurd rfl h
      rw [mul_one]
      exact self_le_pow hp.pos (by omega)
    · calc p = 1 * p := (one_mul p).symm
        _ ≤ p ^ (e - 1) * r := Nat.mul_le_mul (Nat.one_le_pow _ _ hp.pos) hpr
  · calc p ^ e * r = p ^ (e - 1) * p * r := by rw [hpe]
      _ = p * (p ^ (e - 1) * r) := by ring

/-- **Claim M10, Finset form.**  `claimants_C(m) ⊆ claimants_B(m) = {p ∣ m : p² ≤ m}`. -/
theorem claimants_subset {W m : ℕ} (hm : 0 < m) (hcop : Nat.Coprime m W) {p : ℕ}
    (h : ∃ e, ClaimsC W p e m) : p ∈ AlgB.claimants m := by
  obtain ⟨e, hcl⟩ := h
  exact (AlgB.mem_claimants (W := W) hm hcop).mpr (claimsB_of_claimsC hcl)

/-- The strictness witness of §7.1: `847 = 7·11²`.  Algorithm B claims it twice, at `p = 7`
and at `p = 11`; Algorithm C claims it once, in layer `(7,1)` with `r = 121`. -/
theorem claims_847_seven : ClaimsC 30 7 1 847 :=
  ⟨by norm_num, by norm_num, le_rfl, 121,
    Or.inr ⟨by norm_num, by norm_num, by norm_num⟩, Or.inr (by norm_num), by norm_num⟩

/-- … and no layer of `11` claims `847`: `v_11 = 2`, and the cofactor `7 < 11` is inadmissible
while `847 ≠ 11²`. -/
theorem not_claims_847_eleven (e : ℕ) : ¬ ClaimsC 30 11 e 847 := by
  rintro ⟨hp, -, he, r, hadm, -, hm⟩
  have hnd : ¬ (11 : ℕ) ∣ r := Adm.not_dvd (by norm_num) hadm
  obtain ⟨hee, hrr⟩ :=
    valuation_eq (p := 11) (e := e) (e' := 2) (r := r) (r' := 7)
      (by norm_num) hnd (by norm_num) (by rw [← hm]; norm_num)
  subst hrr
  rcases hadm with h | ⟨h, -, -⟩ <;> omega

/-- `847` really is claimed twice by Algorithm B — so the inclusion of Claim M10 is strict. -/
theorem claimsB_847_eleven : AlgB.Claims 30 11 847 :=
  ⟨by norm_num, by norm_num, 77, by norm_num, by norm_num, by norm_num⟩

/-! ### Claim M11 — the streaming min-factor oracle (§8) -/

/-- **Claim M11 (streaming min-factor oracle).**  The claimant with the smallest prime carries
the full min-factor normal form of `n`: `p = spf n`, `e = v_p n`, `r = n/p^e ∈ B_p`.  This —
not the touch count — is the case for Algorithm C. -/
theorem oracle {W p e m : ℕ} (h1 : 1 < m) (hc : ¬ Nat.Prime m) (hcop : Nat.Coprime m W)
    (hcl : ClaimsC W p e m) (hmin : ∀ p' e', ClaimsC W p' e' m → p ≤ p') :
    p = m.minFac ∧ ∃ r, m = p ^ e * r ∧ Bmono p r := by
  obtain ⟨e₀, hcl₀⟩ := coverage h1 hc hcop
  have hple : p ≤ m.minFac := hmin _ _ hcl₀
  obtain ⟨hp, -, he, r, hadm, -, hm⟩ := hcl
  have hpd : p ∣ m := by
    rw [hm]
    exact (dvd_pow_self p (by omega : e ≠ 0)).mul_right r
  have hpp : p = m.minFac := le_antisymm hple (Nat.minFac_le_of_dvd hp.two_le hpd)
  refine ⟨hpp, ?_⟩
  obtain ⟨e', r', he', hB', hm'⟩ := exists_normal_form h1
  have hnd : ¬ p ∣ r := Adm.not_dvd hp hadm
  have hnd' : ¬ p ∣ r' := by
    rw [hpp]; exact hB'.not_dvd (Nat.minFac_prime (by omega))
  have hval : p ^ e * r = p ^ e' * r' := by rw [← hm, hm', hpp]
  obtain ⟨hee, hrr⟩ := valuation_eq hp hnd hnd' hval
  refine ⟨r, hm, ?_⟩
  rw [hpp, hrr]
  exact hB'

/-! ### An executable model, and the §7.1 measurement

Nothing below is used in a proof; it exists so that the claims above can be exercised and the
duplicate accounting of §7.1 can be measured, as `Impl.dupStats` does for Algorithm B. -/

/-- Strip the factors of `p` from `n`: `(v_p n, n / p^{v_p n})`.  `fuel` is any bound `≥ n`. -/
def stripPow (p : ℕ) : ℕ → ℕ → ℕ × ℕ
  | 0, n => (0, n)
  | fuel + 1, n =>
    if 1 < p ∧ p ∣ n then
      let (e, r) := stripPow p fuel (n / p)
      (e + 1, r)
    else (0, n)

/-- The min-factor normal form `(spf n, v_{spf} n, cofactor)` of Claim M1, computably. -/
def normalForm (n : ℕ) : ℕ × ℕ × ℕ :=
  let p := n.minFac
  let (e, r) := stripPow p n n
  (p, e, r)

#eval (List.range 40).filterMap fun n => if 1 < n then some (n, normalForm n) else none

-- Claim M1 checked by evaluation on `2 … 2000`: `p^e·r = n`, `e ≥ 1`, `p ∤ r`.
#eval ((List.range 2000).filter fun n => decide (1 < n)).all fun n =>
  let (p, e, r) := normalForm n
  decide (p ^ e * r = n) && decide (1 ≤ e) && !decide (p ∣ r)

/-- The layers claiming `m` (§7.1): one per claiming prime, i.e. those `p ∣ m` whose cofactor
`m / p^{v_p}` is `1` or `≥ p`. -/
def claimantsC (m : ℕ) : List ℕ :=
  ((List.range (m + 1)).filter fun p => decide (Nat.Prime p ∧ p ∣ m)).filter fun p =>
    let (_, r) := stripPow p m m
    decide (r = 1 ∨ p ≤ r)

/-- §7.1 measured: `(Σ |claimants_C|, Σ |claimants_B|, #composites)` over the `W`-coprime
composites below `N`.  The first is the smaller — by `Θ(N^{2/3}/log N)`, i.e. hardly at all. -/
def dupStatsC (W N : ℕ) : ℕ × ℕ × ℕ :=
  let comps := (List.range N).filter fun m =>
    decide (1 < m ∧ ¬ Nat.Prime m ∧ Nat.gcd m W = 1)
  ((comps.map fun m => (claimantsC m).length).sum,
   (comps.map fun m => (AlgB.claimants m).card).sum,
   comps.length)

#eval dupStatsC 30 2000

-- the smallest witness of Claim M10's strict inclusion, at `W = 30`
#eval (claimantsC 847, (AlgB.claimants 847).toList)

end MinFac
end Primegen